"""Random field synthesis with controlled autocorrelation (Phase 3.3).

- ``exponential_random_field``: isotropic field whose autocorrelation is
  approximately exp(-r/xi) (LER, Phase 5.2 A7). Generated by spectral
  synthesis with PSD ∝ (1 + (2*pi*xi*f)^2)^(-3/2).
- ``gaussian_random_field``: smooth field with Gaussian ACF (CDU / overlay
  drift), generated by Gaussian smoothing of white noise.

Both are deterministic given a ``numpy.random.Generator`` and produce
zero-mean fields scaled to the requested sigma.
"""
from __future__ import annotations

from typing import Tuple

import numpy as np


def exponential_random_field(
    shape: Tuple[int, int],
    xi_nm: float,
    pixel_size_nm: float,
    generator: np.random.Generator,
    sigma: float = 1.0,
) -> np.ndarray:
    M, N = shape
    if xi_nm <= 0 or sigma <= 0:
        return np.zeros(shape, dtype=np.float64)
    fy = np.fft.fftfreq(M, d=float(pixel_size_nm))  # cycles/nm
    fx = np.fft.fftfreq(N, d=float(pixel_size_nm))
    FY, FX = np.meshgrid(fy, fx, indexing="ij")
    k = np.sqrt(FX**2 + FY**2)
    psd = 1.0 / (1.0 + (2.0 * np.pi * xi_nm * k) ** 2) ** 1.5
    phase = generator.uniform(0.0, 2.0 * np.pi, size=shape)
    Z = np.fft.ifft2(np.sqrt(psd) * np.exp(1j * phase)).real
    Z = Z - Z.mean()
    std = Z.std()
    if std > 0:
        Z = Z * (sigma / std)
    return Z


def gaussian_random_field(
    shape: Tuple[int, int],
    xi_nm: float,
    pixel_size_nm: float,
    generator: np.random.Generator,
    sigma: float = 1.0,
) -> np.ndarray:
    from scipy import ndimage

    M, N = shape
    if xi_nm <= 0 or sigma <= 0:
        return np.zeros(shape, dtype=np.float64)
    sigma_px = xi_nm / float(pixel_size_nm)
    white = generator.normal(0.0, 1.0, size=shape)
    Z = ndimage.gaussian_filter(white, sigma=sigma_px, mode="nearest")
    Z = Z - Z.mean()
    std = Z.std()
    if std > 0:
        Z = Z * (sigma / std)
    return Z
